# Generated by Django 4.2.15 on 2025-01-11 08:51

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=150)),
                ('cuisine_type', models.IntegerField(choices=[(1, 'American'), (2, 'Japanese'), (3, 'Italian'), (4, 'Fast Food'), (5, 'Mexican'), (6, 'Indian'), (7, 'Pizza'), (8, 'Vegan'), (9, 'BBQ'), (10, 'Seafood'), (11, 'Steakhouse'), (12, 'Chinese'), (13, 'Mediterranean'), (14, 'Spanish'), (15, 'Asian Fusion'), (16, 'Grilled'), (17, 'French'), (18, 'Thai'), (19, 'Middle Eastern'), (20, 'European'), (21, 'Sizzling Platters'), (22, 'Garden Fresh'), (23, 'Tandoori'), (24, 'Ramen'), (25, 'Fusion'), (26, 'Brunch'), (27, 'Breakfast'), (28, 'Salad'), (29, 'Bistro'), (30, 'Wraps'), (31, 'Mexican Tacos'), (32, 'Asian'), (33, 'Burgers'), (34, 'Classic Pizza'), (35, 'Authentic Sushi'), (36, 'Spicy Curry'), (37, 'BBQ Delights'), (38, 'Fine Steakhouse'), (39, 'Chinese Dumplings'), (40, 'Gourmet Mediterranean'), (41, 'Spanish Tapas'), (42, 'Noodles'), (43, 'BBQ and Grill'), (44, 'Gourmet French'), (45, 'Exquisite Thai')], default=None)),
                ('phone_number', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('table_number', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('capacity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('at_restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_start_time', models.DateTimeField()),
                ('booking_end_time', models.DateTimeField(blank=True, null=True)),
                ('number_of_guests', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='confirmed', max_length=20)),
                ('food_restrictions', models.CharField(blank=True, max_length=200, null=True)),
                ('special_requests', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('table_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.table')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
