# Generated by Django 4.2.15 on 2025-01-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
