# Generated by Django 4.2.15 on 2024-08-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('landing', '0003_delete_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=150)),
                ('cuisine_type', models.IntegerField(choices=[(1, 'Italian'), (2, 'American'), (3, 'Mexican'), (4, 'Chinese'), (5, 'Indian'), (6, 'Thai'), (7, 'Japanese'), (8, 'German'), (9, 'French'), (10, 'Spanish'), (11, 'Russian'), (12, 'Vietnamese'), (13, 'Turkish'), (14, 'Indonesian'), (15, 'Brazilian'), (16, 'Egyptian'), (17, 'Greek'), (18, 'Korean'), (19, 'Polish'), (20, 'Czech')], default=None)),
                ('phone_number', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
