# Generated by Django 4.2.15 on 2025-01-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_booking_cancelled_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(default=0, help_text='Full name of the user.', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(default=0, help_text='Phone number of the user.', max_length=20),
            preserve_default=False,
        ),
    ]
