# Generated by Django 4.2.15 on 2024-08-15 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_alter_restaurant_cuisine_type_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(default=None, upload_to='restaurant_images/'),
            preserve_default=False,
        ),
    ]
